// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/url;

# The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.sendgrid.com") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Create a batch ID.
    #
    # + headers - Headers to be sent with the request 
    # + return - Batch ID success response. 
    resource isolated function post v3/mail/batch(CreateMailBatchHeaders headers = {}) returns error? {
        string resourcePath = string `/v3/mail/batch`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a batch ID.
    #
    # + batch_id - Set this parameter to the batch ID that's associated with the mail send you want to retrieve.
    # + headers - Headers to be sent with the request 
    # + return - Batch ID success response. 
    resource isolated function get v3/mail/batch/[string batch_id](GetMailBatchHeaders headers = {}) returns error? {
        string resourcePath = string `/v3/mail/batch/${getEncodedUri(batch_id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Send Email with Twilio SendGrid.
    #
    # + headers - Headers to be sent with the request 
    # + return - Accepted 
    resource isolated function post v3/mail/send(record {record {int group_id; int[] groups_to_display?;} asm?; record {string content; string content_id?; Disposition disposition = "attachment"; string filename; string 'type?;}[] attachments?; string batch_id?; CategoriesItemsString[] categories?; record {string 'type; string value;}[] content?; string custom_args?; MailFrom 'from; record {} headers?; string ip_pool_name?; record {record {boolean enable?;} bypass_bounce_management?; record {boolean enable?;} bypass_list_management?; record {boolean enable?;} bypass_spam_management?; record {boolean enable?;} bypass_unsubscribe_management?; record {boolean enable?; string html?; string text?;} footer?; record {boolean enable?;} sandbox_mode?;} mail_settings?; record {MailTo[] bcc?; MailTo[] cc?; record {} custom_args?; record {} dynamic_template_data?; MailFrom 'from?; record {} headers?; int send_at?; string subject?; record {|string...;|} substitutions?; MailTo[] to;}[] personalizations; MailTo reply_to?; MailTo[] reply_to_list?; int send_at?; string subject?; string template_id?; record {record {boolean enable?; boolean enable_text?;} click_tracking?; record {boolean enable?; string utm_campaign?; string utm_content?; string utm_medium?; string utm_source?; string utm_term?;} ganalytics?; record {boolean enable?; string substitution_tag?;} open_tracking?; record {boolean enable?; string html?; string substitution_tag?; string text?;} subscription_tracking?;} tracking_settings?;} payload, SendMailHeaders headers = {}) returns error? {
        string resourcePath = string `/v3/mail/send`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}

# Get Encoded URI for a given value.
#
# + value - Value to be encoded
# + return - Encoded string
isolated function getEncodedUri(anydata value) returns string {
    string|error encoded = url:encode(value.toString(), "UTF8");
    if encoded is string {
        return encoded;
    } else {
        return value.toString();
    }
}

public type CategoriesItemsString string;

# Represents the Headers record for the operation: SendMail
public type SendMailHeaders record {
    # Use this header when sending a gzip compressed mail body. Mail body compression is available to some high volume accounts. Submit a [request to support](https://support.sendgrid.com/hc/en-us) to have gzip enabled on your account.
    ContentEncoding Content\-Encoding?;
};

public type AttachmentsItemsObject record {
    string content;
    string content_id?;
    Disposition disposition = "attachment";
    string filename;
    string 'type?;
};

public type MailFrom record {
    # The email address from which messages are sent. This address should be a verified sender in your Twilio SendGrid account. Email addresses specified in `personalizations` will override addresses set at the message level outside of the `personalizations` object.
    string email;
    # A name or title associated with the email address such as "Support" or "Alex".
    string name?;
};

public type Disposition "inline"|"attachment";

public type ContentEncoding "gzip";

# Represents the Headers record for the operation: CreateMailBatch
public type CreateMailBatchHeaders record {
    # Use the `on-behalf-of` header to make API calls for a particular Subuser through the parent account. You can use this header to automate bulk updates or to administer a Subuser without changing the authentication in your code. You will use the parent account's API key when using this header.
    string on\-behalf\-of?;
};

public type PersonalizationsItemsObject record {
    MailTo[] bcc?;
    MailTo[] cc?;
    record {} custom_args?;
    record {} dynamic_template_data?;
    MailFrom 'from?;
    record {} headers?;
    int send_at?;
    string subject?;
    record {|string...;|} substitutions?;
    MailTo[] to;
};

public type ContentItemsObject record {
    string 'type;
    string value;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: GetMailBatch
public type GetMailBatchHeaders record {
    # Use the `on-behalf-of` header to make API calls for a particular Subuser through the parent account. You can use this header to automate bulk updates or to administer a Subuser without changing the authentication in your code. You will use the parent account's API key when using this header.
    string on\-behalf\-of?;
};

public type MailTo record {
    # An email address to which a message is sent. Email addresses specified in `personalizations` will override addresses set at the message level outside of the `personalizations` object.
    string email;
    # A name or title associated with the email address such as "Alex".
    string name?;
};
