// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /channel-connections/{channelConnectionId}"
  | "DELETE /properties/{propertyId}"
  | "DELETE /room-types/{roomTypeId}"
  | "DELETE /staff-accounts/{staffAccountId}"
  | "GET /channel-connections"
  | "GET /channel-connections/{channelConnectionId}/sync-events"
  | "GET /health"
  | "GET /me/reservations"
  | "GET /properties"
  | "GET /properties/{propertyId}"
  | "GET /properties/{propertyId}/room-types"
  | "GET /reports/bookings"
  | "GET /reports/revenue"
  | "GET /reservations"
  | "GET /reservations/{reservationId}"
  | "GET /room-types/{roomTypeId}/availability"
  | "GET /room-types/{roomTypeId}/rate-plans"
  | "GET /staff-accounts"
  | "POST /channel-bookings"
  | "POST /channel-connections"
  | "POST /me/reservations"
  | "POST /me/reservations/{reservationId}/cancel"
  | "POST /properties"
  | "POST /properties/{propertyId}/room-types"
  | "POST /reservations"
  | "POST /reservations/{reservationId}/cancel"
  | "POST /reservations/{reservationId}/check-in"
  | "POST /reservations/{reservationId}/check-out"
  | "POST /room-types/{roomTypeId}/rate-plans"
  | "POST /staff-accounts"
  | "PUT /channel-connections/{channelConnectionId}"
  | "PUT /properties/{propertyId}"
  | "PUT /reservations/{reservationId}"
  | "PUT /room-types/{roomTypeId}"
  | "PUT /room-types/{roomTypeId}/availability"
  | "PUT /staff-accounts/{staffAccountId}";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /channel-connections/{channelConnectionId}": { kind: "scope", scope: "channel-connections:manage" },
  "DELETE /properties/{propertyId}": { kind: "scope", scope: "properties:manage" },
  "DELETE /room-types/{roomTypeId}": { kind: "scope", scope: "room-inventory:manage" },
  "DELETE /staff-accounts/{staffAccountId}": { kind: "scope", scope: "staff-accounts:manage" },
  "GET /channel-connections": { kind: "scope", scope: "channel-connections:read" },
  "GET /channel-connections/{channelConnectionId}/sync-events": { kind: "scope", scope: "sync-events:read" },
  "GET /health": { kind: "public" },
  "GET /me/reservations": { kind: "scope", scope: "reservations:read" },
  "GET /properties": { kind: "public" },
  "GET /properties/{propertyId}": { kind: "public" },
  "GET /properties/{propertyId}/room-types": { kind: "public" },
  "GET /reports/bookings": { kind: "scope", scope: "reports:read" },
  "GET /reports/revenue": { kind: "scope", scope: "reports:read" },
  "GET /reservations": { kind: "scope", scope: "reservations:read-all" },
  "GET /reservations/{reservationId}": { kind: "scope", scope: "reservations:read-all" },
  "GET /room-types/{roomTypeId}/availability": { kind: "public" },
  "GET /room-types/{roomTypeId}/rate-plans": { kind: "public" },
  "GET /staff-accounts": { kind: "scope", scope: "staff-accounts:read" },
  "POST /channel-bookings": { kind: "public" },
  "POST /channel-connections": { kind: "scope", scope: "channel-connections:manage" },
  "POST /me/reservations": { kind: "scope", scope: "reservations:create" },
  "POST /me/reservations/{reservationId}/cancel": { kind: "scope", scope: "reservations:cancel" },
  "POST /properties": { kind: "scope", scope: "properties:manage" },
  "POST /properties/{propertyId}/room-types": { kind: "scope", scope: "room-inventory:manage" },
  "POST /reservations": { kind: "scope", scope: "reservations:manage" },
  "POST /reservations/{reservationId}/cancel": { kind: "scope", scope: "reservations:manage" },
  "POST /reservations/{reservationId}/check-in": { kind: "scope", scope: "reservations:manage" },
  "POST /reservations/{reservationId}/check-out": { kind: "scope", scope: "reservations:manage" },
  "POST /room-types/{roomTypeId}/rate-plans": { kind: "scope", scope: "room-inventory:manage" },
  "POST /staff-accounts": { kind: "scope", scope: "staff-accounts:manage" },
  "PUT /channel-connections/{channelConnectionId}": { kind: "scope", scope: "channel-connections:manage" },
  "PUT /properties/{propertyId}": { kind: "scope", scope: "properties:manage" },
  "PUT /reservations/{reservationId}": { kind: "scope", scope: "reservations:manage" },
  "PUT /room-types/{roomTypeId}": { kind: "scope", scope: "room-inventory:manage" },
  "PUT /room-types/{roomTypeId}/availability": { kind: "scope", scope: "room-inventory:manage" },
  "PUT /staff-accounts/{staffAccountId}": { kind: "scope", scope: "staff-accounts:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
