// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/url;

# ASSUMED interface, written under the user's authorization, covering only the operations this design calls: initiate a hosted-page card payment for a booking, and receive the gateway's payment notification callback. Sampath Bank's real IPG is a merchant-onboarded, credential-gated integration with no publicly published API document; this models the common hosted-payment-page pattern most bank IPGs in this region use (merchant ID + HMAC-SHA256 request/response hash, browser redirect to a hosted card page, server-to-server payment notification). Uncertain: the exact field names and hash algorithm/order, the redirect parameter names, the notification payload shape, and refund/void support. Treat this as a placeholder contract to validate integration logic against, not the provider's real wire format — confirm and replace once merchant onboarding documentation is available.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://ipg.sampath.lk") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Start a hosted-page card payment for a booking
    #
    # + headers - Headers to be sent with the request 
    # + return - Payment session created; redirect the guest to redirectUrl 
    resource isolated function post payments/initiate(PaymentInitiationRequest payload, map<string|string[]> headers = {}) returns PaymentInitiationResponse|error {
        string resourcePath = string `/payments/initiate`;
        map<anydata> headerValues = {...headers};
        headerValues["X-Merchant-Hash"] = self.apiKeyConfig.X\-Merchant\-Hash;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Receive the gateway's server-to-server payment outcome notification
    #
    # + headers - Headers to be sent with the request 
    # + return - Notification acknowledged 
    resource isolated function post payments/notify(PaymentNotification payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/payments/notify`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }
}

# Get Encoded URI for a given value.
#
# + value - Value to be encoded
# + return - Encoded string
isolated function getEncodedUri(anydata value) returns string {
    string|error encoded = url:encode(value.toString(), "UTF8");
    if encoded is string {
        return encoded;
    } else {
        return value.toString();
    }
}

public type PaymentInitiationRequest record {
    string merchantId;
    # The reservation id this payment settles
    string orderId;
    decimal amount;
    # ISO currency code, must match the property's configured currency
    string currency;
    # URL the guest is redirected back to after paying
    string returnUrl;
};

public type PaymentInitiationResponse record {
    # Hosted card-entry page the guest is redirected to
    string redirectUrl?;
    string sessionId?;
};

public type PaymentNotification record {
    string orderId?;
    string sessionId?;
    "approved"|"declined"|"cancelled" status?;
    decimal amount?;
    string providerReference?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # HMAC-SHA256 request hash computed from the merchant ID, order details and the merchant's hash secret, per Sampath's merchant integration guide.
    @display {label: "", kind: "password"}
    string X\-Merchant\-Hash;
|};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
