// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "channel-connections:manage"
  | "channel-connections:read"
  | "properties:manage"
  | "reports:read"
  | "reservations:cancel"
  | "reservations:create"
  | "reservations:manage"
  | "reservations:read"
  | "reservations:read-all"
  | "room-inventory:manage"
  | "staff-accounts:manage"
  | "staff-accounts:read"
  | "sync-events:read";

export type Role =
  | "ChannelOperator"
  | "FrontDeskAgent"
  | "Guest"
  | "HotelManager";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["channel-connections:manage", "channel-connections:read", "properties:manage", "reports:read", "reservations:cancel", "reservations:create", "reservations:manage", "reservations:read", "reservations:read-all", "room-inventory:manage", "staff-accounts:manage", "staff-accounts:read", "sync-events:read"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["ChannelOperator", "FrontDeskAgent", "Guest", "HotelManager"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "ChannelOperator": ["channel-connections:manage", "channel-connections:read", "sync-events:read"],
  "FrontDeskAgent": ["reservations:manage", "reservations:read-all"],
  "Guest": ["reservations:cancel", "reservations:create", "reservations:read"],
  "HotelManager": ["properties:manage", "reports:read", "reservations:read-all", "room-inventory:manage", "staff-accounts:manage", "staff-accounts:read"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "ChannelOperator": ["ChannelOperators"],
  "FrontDeskAgent": ["FrontDeskStaff"],
  "Guest": [],
  "HotelManager": ["HotelManagers"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "ChannelOperator": [],
  "FrontDeskAgent": [],
  "Guest": [],
  "HotelManager": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
